version: "3"

services:
  web:
    build:
      context: .
      target: dev
    image: path_mapper/web
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      MIX_ENV: null
    user: '1000:1000'
