# frozen_string_literal: true

$LOAD_PATH.unshift(__dir__) unless $LOAD_PATH.include?(__dir__)

require 'path_mapper/id'
require 'path_mapper/png'
require 'path_mapper/token'
require 'path_mapper/progress'
require 'path_mapper/config'
require 'path_mapper/server'
require 'path_mapper/asset'
require 'path_mapper/blob'
require 'path_mapper/snapshot'
require 'path_mapper/xcf'
require 'path_mapper/org'
require 'path_mapper/character'
require 'path_mapper/library'
require 'path_mapper/load_list'
require 'path_mapper/loading'
require 'path_mapper/state'
require 'path_mapper/maps'
require 'path_mapper/notify'
require 'path_mapper/kind'
require 'path_mapper/upload'
require 'path_mapper/cli'
